### ISSUE TITLE
specify a GPU when multiple GPUs present

### ISSUE THREAD

**Issue by heejongkim** [bittremieux/ANN-SoLo#4]
Hi,
It seems like ANN-Solo always takes the GPU 0 to process its job.
I wonder it's possible either utilizing the multiple GPUs for a single job or specifying which GPU should be utilized for a single job so that I can run multiple ANN-Solo instances at the same time.

Thank you so much.

**Comment by bittremieux** [comment]
1. The latest ANN-SoLo release (v0.2.4) only supports a single GPU, and will indeed always use GPU 0. To use another GPU you can use the `CUDA_VISIBLE_DEVICES` environment variable. For example, if you have two GPUs: `CUDA_VISIBLE_DEVICES=1 python -m ann_solo.ann_solo ...` will use the second GPU.
2. The current `dev` branch contains support for multiple GPUs. In this case, all available GPUs will be used, but you can restrict which GPUs are used with the `CUDA_VISIBLE_DEVICES` environment variable again. This functionality _should_ work, but it hasn't been fully tested yet.

**Comment by heejongkim** [comment]
Oh nice!
Thank you so much!
Will give it a shot.
